// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqsscB2hZ1cURROQiLbj7lhQvNzheaRcg',
    appId: '1:724733912319:web:24e9a9519f4334e1dcd8ca',
    messagingSenderId: '724733912319',
    projectId: 'lsmg-7238d',
    authDomain: 'lsmg-7238d.firebaseapp.com',
    storageBucket: 'lsmg-7238d.firebasestorage.app',
    measurementId: 'G-NS95FLREV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNXURL9GDk9ncdVUP7yaSDmwq39IdTr3E',
    appId: '1:724733912319:android:1c00e99f1dfac2e3dcd8ca',
    messagingSenderId: '724733912319',
    projectId: 'lsmg-7238d',
    storageBucket: 'lsmg-7238d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIsxioRf6zsBfwVSss2GuHan8LLc7haMY',
    appId: '1:724733912319:ios:ea6fbe6fd0287369dcd8ca',
    messagingSenderId: '724733912319',
    projectId: 'lsmg-7238d',
    storageBucket: 'lsmg-7238d.firebasestorage.app',
    iosBundleId: 'com.example.lsm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIsxioRf6zsBfwVSss2GuHan8LLc7haMY',
    appId: '1:724733912319:ios:ea6fbe6fd0287369dcd8ca',
    messagingSenderId: '724733912319',
    projectId: 'lsmg-7238d',
    storageBucket: 'lsmg-7238d.firebasestorage.app',
    iosBundleId: 'com.example.lsm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqsscB2hZ1cURROQiLbj7lhQvNzheaRcg',
    appId: '1:724733912319:web:c03aed3f6e989125dcd8ca',
    messagingSenderId: '724733912319',
    projectId: 'lsmg-7238d',
    authDomain: 'lsmg-7238d.firebaseapp.com',
    storageBucket: 'lsmg-7238d.firebasestorage.app',
    measurementId: 'G-BLSB0VP4X2',
  );
}
